### ISSUE TITLE
nupnp address should be stored in a config file for test customization

### ISSUE THREAD

**Issue by nojunpark** [fxbox/foxbox#106]
CR mentioned that  nupnp server address is currently hardcoded and there is no simple mechanism to pass down command arguments to adapters. However, the plan is to have the option to store it in a global config parameter which could relatively easily be overridden.

**Comment by mcav** [comment]
What kind of configuration do we want? Command-line flags? Environment variables? JSON file?

**Comment by nojunpark** [comment]
For me, command line flag would be easiest to incorporate, however @cr mentioned that this should reside in a config file (probably in JSON format), and I'm fine with any implementation.

**Comment by michielbdejong** [comment]
This is about the nupnp for device pairing (Box-Hue), _not_ for client pairing (App-Box), right?

**Comment by nojunpark** [comment]
that's correct, this nupnp is used to find the philips hue hub: https://github.com/fxbox/foxbox/blob/master/src/adapters/philips_hue/mod.rs#L52

**Comment by JohanLorenzo** [comment]
I'll give it a try

**Comment by nojunpark** [comment]
Closed since we have #165
