### ISSUE TITLE
Proper shutdown sequence

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#111]
We don't have a shutdown sequence, but we really should have one.  Would be useful to stop/restart when updating for instance.

@mcav is that something you would be interested in?

**Comment by mcav** [comment]
Sure, I can take a stab. You essentially mean providing a (1) shutdown event/callback dispatched to adapters/etc to allow them to shut down gracefully, and (2) a shutdown function that we can call to force the app to terminate, @fabricedesre?

**Comment by fabricedesre** [comment]
Yes to (1) and (2), and (3) would be triggering shutdown cleanly through unix signals.
