### ISSUE TITLE
Intermittent test failures in service_router

### ISSUE THREAD

**Issue by cr** [fxbox/foxbox#114]
I'm getting intermittent test failures running `cargo test`:
- `test service_router::service_router::services::should_make_service_available ... FAILED`
- `test service_router::service_router::services::should_return_an_error_if_no_service_was_found ... FAILED` 
- `test service_router::service_router::services::should_create_list.json ... FAILED`

The error is always:

`thread 'service_router::service_router::services::should_make_service_available' panicked at 'called `Result::unwrap()` on an `Err` value: IronError { error: StringError("Unauthorized"), response: HTTP/1.1 401 Unauthorized Unauthorized`

Looks like another init race condition.

**Comment by cr** [comment]
A workaround is running `cargo test` and `git commit` with `RUST_TEST_THREADS=1`.

**Comment by mcav** [comment]
Is there a downside to using `RUST_TEST_THREADS=1`? Are we doing something systemically wrong that needs fixing in our code, or is this just an inconvenience in terms of how the test harness works?

**Comment by ferjm** [comment]
@cr are you still seeing these intermitents?

**Comment by cr** [comment]
Nope, they are completely gone. Closing.
