### ISSUE TITLE
Authentication seems broken

### ISSUE THREAD

**Issue by dhylands** [fxbox/foxbox#123]
I did a git clean -x -d -f   to remove all files not checked into github

I then did a cargo build

I then browsed to http://localhost:3000 and was asked to enter my admin password (rather than the ask/confirm). Checking the filesystem, users_db.sqlite doesn't even exist yet. And of course, because I haven't set a password, all passwords come back as unauthorized.

So something about authentication seems totally broken.

Tagging @ferjm so that he sees this.

Running with RUST_LOG=foxbox=trace cargo run yields no interesting information.

If I enter a password and click Signin then I get back an Unauthorized error, and an empty users_db.sqlite is created. If I browse the database using sqlitebrowser it shows no rows in the table.

**Comment by dhylands** [comment]
I have 2 computers, and from the other computer (the very first one I attached to, it says I'm logged in as admin, even though there is no users_db.sqlite file

**Comment by nojunpark** [comment]
Also, shouldn't users_db.sqlite be removed when cargo clean is run? with this file persisting, rebuilding the foxbox won't let the user to set the password.

**Comment by ferjm** [comment]
We discussed this over IRC.

> I then browsed to http://localhost:3000 and was asked to enter my admin password (rather than the ask/confirm). Checking the filesystem, users_db.sqlite doesn't even exist yet. And of course, because I haven't set a password, all passwords come back as unauthorized.

The issue seemed to have started from the fact that there were already a session stored locally on Dave's browser but the user's db was clean.

To fix this, I'm going to split the setup UI from the login UI. I'll file a new issue for this.

Also the test client I propose to use as an alternative to manual requests wasn't helping at all.

> Also, shouldn't users_db.sqlite be removed when cargo clean is run? with this file persisting, rebuilding the foxbox won't let the user to set the password.

Good point. I'll file a new issue for this as well.

**Comment by ferjm** [comment]
I'm closing this one in favor of #125 and #126.
