### ISSUE TITLE
Cargo clean should remove user's db

### ISSUE THREAD

**Issue by ferjm** [fxbox/foxbox#126]

**Comment by dhylands** [comment]
I don't know that this is desirable. cleaning is just cleaning from a building perspective. It doesn't mean I want to wipe all of the data on my foxbox.

I think that it would better to have alll of the user data (snapshots, user_db, etc) stored outside the source tree.

**Comment by ferjm** [comment]
> I think that it would better to have alll of the user data (snapshots, user_db, etc) stored outside the source tree.

That sounds appropriate to me as well.

#142 will help to solve this.
