### ISSUE TITLE
Integrate Thinkerbell

### ISSUE THREAD

**Issue by Yoric** [fxbox/foxbox#127]
We need to make Thinkerbell usable from the FoxBox, and hey, while we're at it, let's make it an `Adapter`, with the following services:
### Setters
- Add a new rule.
### Getters
- Is the rule enabled/disabled?
## Setters
- Remove the rule.
- Enable/disable the rule.
# Blockers
- [ ] https://github.com/fxbox/thinkerbell/issues/36

**Comment by Yoric** [comment]
Cc @fabricedesre , @mcav .

**Comment by fabricedesre** [comment]
lgtm

**Comment by mcav** [comment]
By `rule`, you mean `script`?

**Comment by Yoric** [comment]
@mcav ah, right, indeed.
