### ISSUE TITLE
Store database and config files in a profile directory.

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#142]
Right now they end up in the directory foxbox was launched from.

**Comment by jedireza** [comment]
Just came across this new create [`preferences`](https://crates.io/crates/preferences) maybe it could help or inspire a solution.

https://crates.io/crates/preferences

**Comment by hfiguiere** [comment]
I'll have a PR for fxbox/users#53 that will allow setting the path for the user DB. It should help implementing this.

**Comment by fabricedesre** [comment]
Working on that today.

**Comment by fabricedesre** [comment]
Fixed by https://github.com/fxbox/foxbox/issues/184
