### ISSUE TITLE
CORS headers on login 401

### ISSUE THREAD

**Issue by michielbdejong** [fxbox/foxbox#143]
When you use the wrong 'admin' password to try to log in to the app, you see a NetworkError instead of a 'Wrong password' error, and a CORS-related error in the console:

<img width="1276" alt="screen shot 2016-03-07 at 10 08 55" src="https://cloud.githubusercontent.com/assets/408412/13564847/c4fae0ec-e44c-11e5-9bb0-2ca7e3e6cd0c.png">

**Comment by ferjm** [comment]
https://github.com/fxbox/foxbox/commit/b1e14fee02cbb5d1d71d785496a00f40426ce38d
