### ISSUE TITLE
Register on http://knilxof.org:4242/register?ip=127.0.0.1 at start-up

### ISSUE THREAD

**Issue by michielbdejong** [fxbox/foxbox#145]
Right now this is a manual step in https://public.etherpad-mozilla.org/p/project-link-discovery#lineNumber=10

**Comment by arcturus** [comment]
Don't understand why we need to register 127.0.0.1?

Right now on startup if you pass the -r parameter it proceed against the registration server:

``` bash
RUST_LOG=info cargo run -- -r http://knilxof.org:4242/register
```

**Comment by michielbdejong** [comment]
Right, I just had forgotten to pass the -r parameter, that's why it wasn't working for me :)
