### ISSUE TITLE
foxbox.conf error should be slienced

### ISSUE THREAD

**Issue by nojunpark** [fxbox/foxbox#148]
Upon executing fxbox, following error message is shown:
ERROR:foxbox::config_store: Unable to open configuration file foxbox.conf: No such file or directory (os error 2).  According to fabrice, this is actually not an error.
ccing @cr for resolution.

**Comment by JohanLorenzo** [comment]
Fixed in #138

**Comment by cr** [comment]
...which has landed. Closing.
