### ISSUE TITLE
Rename --name argument to more appropriate --local-name

### ISSUE THREAD

**Issue by ferjm** [fxbox/foxbox#173]
```
➜  foxbox git:(pagekite) ✗ cargo run -- --name box1.knilxof.org
     Running `target/debug/foxbox --name box1.knilxof.org`
2016-03-09 17:37:41.467: INFO  Starting registration with http://localhost:4242/register
2016-03-09 17:37:41.468: INFO  Got ip address: 192.168.1.40
WARNING: Your platform is not supported by real mDNS adapter, fake adapter is used!
WARNING: Your platform is not supported by real mDNS adapter, fake adapter is used!
WARNING: Your platform is not supported by real mDNS adapter, fake adapter is used!
2016-03-09 17:37:41.471: INFO  Unable to send request to http://localhost:4242/register?ip=192.168.1.40
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: nodename nor servname provided, or not known") }) }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Process didn't exit successfully: `target/debug/foxbox --name box1.knilxof.org` (exit code: 101)
```

**Comment by ferjm** [comment]
CC @azasypkin

**Comment by azasypkin** [comment]
Yep, we change host name via avahi daemon that is Linux only. For OSX I didn't want to be silent if this option is used, I'd implenent OSX mdns adapter via any OSX compatible thing, but I don't have OSX to even test it :/ Is there any better idea that I can do to make life of OSX users easier?

**Comment by ferjm** [comment]
Just ignoring the option and not panicking would work for me :)

We may want to reuse the --name option for something else (like tunnel options)

**Comment by azasypkin** [comment]
> Just ignoring the option and not panicking would work for me :)

Okay, will fix that then :)

**Comment by azasypkin** [comment]
@ferjm hmm, I see you use `--name box1.knilxof.org`, I pass it directly to `avah_set_host_name` that expects just host name (not fqdn, cause it always `.local` domain):/

**Comment by azasypkin** [comment]
should we introduce different parameters then? like `--remote-name` and `--local-name` or ....

**Comment by ferjm** [comment]
`--remote-name` and `--local-name` sounds good to me. Let's just rename `--name` to `--local-name` for now and we will add the other parameter when it's actually needed (once we have all the DNS and tunneling stuff ready). Thanks!

**Comment by azasypkin** [comment]
Good, @fabricedesre do you have any objections to changing `-n (--name)` to something like `-l (--local-name)` to clearly separate "local" and "remote" names? I suspect they will be different and coexist at the same time.

@ferjm, regarding using `--local-name` on OSX - I suspect you just need to change OSX Bonjour name before running foxbox and then run it with the same `--local-name actual-bonjor-name` so that internal HttpServer can bind on the _existing_ `actual-bonjor-name.local` address without `panic!`.

**Comment by ferjm** [comment]
Ok, I'll try that. Thanks.

FWIW #179 is adding `--remote-name`

**Comment by fabricedesre** [comment]
Sure, renaming to `--local-name` is fine.
