### ISSUE TITLE
Should we remove "auth" query string token/header from the Iron Request before adapters start to handle it?

### ISSUE THREAD

**Issue by azasypkin** [fxbox/foxbox#204]
In https://github.com/fxbox/users/issues/68 (https://github.com/fxbox/users/pull/69) "auth" query string token support will be added. It will kind of become more apparent, especially if adapter parses query string for api-specific parameters.

So would it do any harm if adapters can access auth token?

**Comment by ferjm** [comment]
Some adapters like the [WebPush one](https://github.com/fxbox/foxbox/issues/246) need to get the auth token containing the user id.

For now, it's fine to progress the auth token to the adapters cause all of them are built in and under our control, but I think at some point we want to allow 3rd party adapters. I'm not sure what's the story for 3rd party adapters, but I guess we should have a way to limit what they can do and the data they can obtain.

@fabricedesre @cr wdyt?

**Comment by fabricedesre** [comment]
Adapters don't get access to the raw http request anymore. But we need them to get some opaque user identifier at least for their own book keeping.
3rd party adapters will run OOP, and will need that too. What we have to decide in general is whether we want to allow an adpater to call another one and expect the user token to be sharable.

**Comment by ferjm** [comment]
We are already giving the user id to the adapters but, as Fabrice mentioned above, the raw auth header is not being sent. So I think we can close this one.
