### ISSUE TITLE
Re-enable kcov

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#236]
I had to disable it because it's segfaulting since https://github.com/fxbox/foxbox/commit/790b67b94da5644781cebef23e2f616de27f10a3 landed.

I can reproduce the crash locally, even with a kcov from the tip of upstream.
In gdb, here's what we get:
(gdb)  run '--exclude-path=~/.cargo, /home/fabrice/dev/foxbox/tools/../src/stubs, /home/fabrice/dev/foxbox/tools/../target' --coveralls-id=no-job-id /home/fabrice/dev/foxbox/tools/../target/coverage-report/ /home/fabrice/dev/foxbox/tools/../target/debug/foxbox-7c1b57735a989781
Starting program: /home/fabrice/dev/kcov/src/kcov '--exclude-path=~/.cargo, /home/fabrice/dev/foxbox/tools/../src/stubs, /home/fabrice/dev/foxbox/tools/../target' --coveralls-id=no-job-id /home/fabrice/dev/foxbox/tools/../target/coverage-report/ /home/fabrice/dev/foxbox/tools/../target/debug/foxbox-7c1b57735a989781
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1574700 (LWP 27186)]
XXX solibThreadParse Opening /home/fabrice/dev/foxbox/tools/../target/coverage-report//foxbox-7c1b57735a989781/kcov-solib.pipe
XXX solibThreadParse Opening /home/fabrice/dev/foxbox/tools/../target/coverage-report//foxbox-7c1b57735a989781/kcov-solib.pipe
kcov: Process exited with signal 11 (SIGSEGV) at 0x555556c3afd7
[New Thread 0x7ffff0d73700 (LWP 27189)]
[Thread 0x7ffff0d73700 (LWP 27189) exited]
kcov: warning: coveralls write failed: {"message":"Couldn't find a repository matching this job.","error":true}

Program received signal SIGTERM, Terminated.
[Switching to Thread 0x7ffff1574700 (LWP 27186)]
0x00007ffff6f6159d in open64 () at ../sysdeps/unix/syscall-template.S:81
81  ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ffff6f6159d in open64 () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000450d77 in open (__oflag=0, __path=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/fcntl2.h:53
#2  SolibHandler::solibThreadParse (this=0xadbad0) at /home/fabrice/dev/kcov/src/solib-handler.cc:129
#3  0x0000000000450f68 in SolibHandler::solibThreadMain (this=<optimized out>) at /home/fabrice/dev/kcov/src/solib-handler.cc:170
#4  SolibHandler::threadStatic (pThis=0xadbad0) at /home/fabrice/dev/kcov/src/solib-handler.cc:179
#5  0x00007ffff6f586aa in start_thread (arg=0x7ffff1574700) at pthread_create.c:333
#6  0x00007ffff6a76e9d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) quit

**Comment by fabricedesre** [comment]
And I forgot to flag @JohanLorenzo

**Comment by JohanLorenzo** [comment]
I can't repro locally on neither the current master nor 790b67b. As @fabricedesre mentioned on IRC, it's very likely related to libc.
My local machine has glibc 2.23, whereas Travis runs on Ubuntu precise, which is [blocked at 2.15](http://packages.ubuntu.com/precise/libc6). In order to fix it, we could either:
- force upgrade Ubuntu to 2.23 -- bad long term solution, it might break other dependencies hold by the package manager.
- Make our own kcov binary and let travis use it. I'm not sure if we'll hit some linking issues. I'll give it a try.

Edit: I managed to repro on a docker image running ubuntu 12.04.5
