### ISSUE TITLE
Figure out how to take advantage of threads in the Taxonomy Router

### ISSUE THREAD

**Issue by Yoric** [fxbox/foxbox#243]
The architecture of Iron requires all `Handler`s to be functions that implement `Fn(Request) -> Response + Sync`.

This has two drawbacks:
- since the function is `Sync`, we cannot easily manipulate e.g. channels;
- since the function is sync, we cannot simply use asynchronous functions from within it.

For the moment, for deliverable 1, the Taxonomy Router simply grabs a lock that it holds until it has provided a response. This is pretty bad for performance, as we cannot have two simultaneous requests to the Taxonomy Router executed concurrently.

Opening this issue to discuss better ways to implement this.

Cc @fabricedesre

**Comment by Yoric** [comment]
# Plan 1

The read-write lock.

## AdapterManager

The AdapterManager should support a form of Read-Write Lock: at any time, it should be executing either any number of concurrent reads or a single write. Implementing this may need some refactoring, e.g. to  get of the fields "last seen" & co that we don't use at the moment.

To take advantage of this, we need to:
1. change the current architecture of the AdapterManager that has a single execution thread and actually execute the code on the calling thread;
2. make sure that the back-end of the `AdapterManager` is `Sync`, without resorting to Mutexes (hard part);
3. acquire/release the Read-Write Lock as needed.

## Taxonomy Router

If we manage this, the Taxonomy Router won't need a `Mutex` anymore.

**Comment by Yoric** [comment]
# Plan 2

Shorter Mutex (a simpler variation of the above).

## AdapterManager
1. change the current architecture of the AdapterManager that has a single execution thread and actually executes the code on the calling thread;
2. wrap all the back-end data behind a `Mutex`;
3. whenever a request arrives, grab the `Mutex` only as long as necessary (typically, long enough to extract the request that will be passed to the `Adapter`s).

## Taxonomy Router

If we manage this, the Taxonomy Router won't need a Mutex anymore.

**Comment by fabricedesre** [comment]
That would also help with adapters that manage services dynamically if that allows them to do that on a different thread.

**Comment by Yoric** [comment]
# Plan 3

Assuming that we can have a Sync access to a connection pool, we could move everything to a DBMS and let the DBMS handle concurrency.

In this scheme, tags are stored to disk, while everything else is stored in memory.

**Comment by fabricedesre** [comment]
yes, it's worth checking if https://crates.io/crates/r2d2 and https://crates.io/crates/r2d2_sqlite would fit the bill.

**Comment by Yoric** [comment]
I think that it is possible with r2d2. I first need to find out whether sqlite supports databases that have combinations of on-disk tables (for tags and last-update timestamps) and in-memory tables (for the rest, that's purely dynamic).

**Update** This seems impossible. So I have the choice between storing to disk data that I don't care about or not using a db.

**Comment by fabricedesre** [comment]
Worst case we flush the dynamic tables at startup?

**Comment by fabricedesre** [comment]
And I don't think we can combine in memory and on-disk tables in the same DB with sqlite.

**Comment by Yoric** [comment]
I have an advanced prototype of Plan 1:
- the AdapterManager has a RwLock;
- only the operations that add/remove adapters, services, channels or tags need to acquire the write lock;
- `fetch`/`send` operations need to acquire the read lock, but release it before talking to the adapter;
- I'm still trying to figure out how to make `watch` operations release the lock early.
