### ISSUE TITLE
We need an API to find out which devices are available

### ISSUE THREAD

**Issue by Yoric** [fxbox/foxbox#25]
We need to provide an API that lets applications find out which devices are available for a specific purpose. This API will be used both server-side (in the rules engine, in Monitor Workers) and client-side (in client web apps).

We need this API at least in REST, as all consumers can be built on top of REST. Ideally, we'd like to provide a concise JS API on top of the REST API. It would be useful to have this API available to Rust code, too, for the sake of the rules engine and possibly Monitor Workers.

I'll describe a possible API in Rust, because I have attempted to do it in other languages and it was actually more complicated:

``` rust
/// Get the list of all available devices that can fulfill a service.
///
/// # Example
///
///  let devices = get_devices(DeviceKind::RobotFromTheFuture,
///                            &vec![InputCapability::DetectSarahConnor, InputCapability::DetectJohnConnor, InputCapability::IsControlledBySkynet],
///                            &vec![OutputCapability::Terminate]);
///
/// for terminator in devices {
///     // ...
/// }
fn get_devices(&DeviceKind, &Vec<InputCapability>, &Vec<OutputCapability>) -> Vec<Device>
```

This depends heavily on our ongoing efforts on Taxonomy.

Note that JS versions of this API will return a `Promise`, rather than blocking.

**Comment by Yoric** [comment]
Cc @mcav, @jedireza, @davidflanagan .

**Comment by mcav** [comment]
Similarly, is this also covered by taxonomy?

**Comment by Yoric** [comment]
Indeed,
