### ISSUE TITLE
Consider using a pre-built version of kcov in Travis

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#300]
I don't know exactly how much time we would save in Travis, but that can't hurt. Right now we're rebuilding from the same source package over and over.

@JohanLorenzo what do you think?

**Comment by JohanLorenzo** [comment]
It's doable, in a fairly reasonable amount of time. In #236, I built an Ubuntu container that replicates what we have in Travis. I think it's a matter of:
1. creating and publishing 2 docker container (one for Precise, the other for Trusty)
2. making the builds
3. hosting these 2 builds under Github releases
4. updating the coverage scripts

**Comment by JohanLorenzo** [comment]
> 1. creating and publishing 2 docker container (one for Precise, the other for Trusty)

Published for [precise](https://hub.docker.com/r/johanlorenzo/kcov-travis/) and for [trusty](https://hub.docker.com/r/johanlorenzo/kcov-travis-trusty/)

> 1. hosting these 2 builds under Github releases

Published at https://github.com/JohanLorenzo/kcov/releases/tag/v30

> 1. updating the coverage scripts

Handled in #305
