### ISSUE TITLE
Concerned about requiring nightly Rust

### ISSUE THREAD

**Issue by jedireza** [fxbox/foxbox#32]
I just wanted to voice a concern about using features that require us to use nightly Rust. I'd prefer us to only use features available in stable Rust so we can make cutting releases easy and not end up in a situation where we have to refactor (backwards).

For example in https://github.com/fxbox/foxbox/pull/29 we chose to use the `docopt!` macro when we could've just kept the original semantics and got the same functionality.

It's not only the `docopt!` macro. There are features in the `serde_json` crate too IIRC. I was planning to remove `serde_json` and use `rustc_serialize::json` instead.

Now that a lot of us are adding code I think we should be aware and agree how best to handle this, even if that decision is to keep nightly Rust.

Thoughts?

**Comment by hfiguiere** [comment]
I used the macro because we already require nightly - I wouldn't have otherwise. 

Maybe the proper thing at that point is to freeze the nightly requirement and make sure that Foxbox ride the train to Rust 1.8 release.

**Comment by hfiguiere** [comment]
FWIW, 1.8 will be out in 10 weeks (12 from Jan 21st)

**Comment by jedireza** [comment]
Tracking 1.8 to stable and then sticking with stable sounds like a good plan.
