### ISSUE TITLE
Getter methods of Webpush adapter causes Jsonerror

### ISSUE THREAD

**Issue by nojunpark** [fxbox/foxbox#328]
When below methods are callled, before or after the subscriptions/resources are set, it returns 400 (Bad request) with EmptyObject { at: "" }

 Get current subscriptions
    PUT http://localhost:3000/api/v1/channels/get {"select": {"id": "getter:subscription.webpush@link.mozilla.org"}, "value": {"Json": {}}}

Get current resources receiving notifications on
    PUT http://localhost:3000/api/v1/channels/get {"select": {"id": "getter:resource.webpush@link.mozilla.org"}, "value": {"Json": {}}}

Yoric mentioned that it's because an empty JSON body is given.  The proper syntax should be listed in https://wiki.mozilla.org/Connected_Devices/Projects/Project_Link/Taxonomy

**Comment by nojunpark** [comment]
@aosmond I think we need your help here.  cc @Yoric

**Comment by Yoric** [comment]
Instead of

```
PUT http://localhost:3000/api/v1/channels/get {"select": {"id": "getter:subscription.webpush@link.mozilla.org"}, "value": {"Json": {}}}
```

do

```
PUT http://localhost:3000/api/v1/channels/get {"id": "getter:subscription.webpush@link.mozilla.org"}
```

I don't know who wrote something false on the Wiki, I'll fix it.

**Comment by nojunpark** [comment]
Awesome! that worked!

**Comment by Yoric** [comment]
Let's close this, then.
