### ISSUE TITLE
Re-enable Hue integration test.

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#338]
I had to disable it when doing the rustup. We were already panic-ing but that got worse with the updated rustc.

@npark-mozilla @isabelrios @JohanLorenzo

**Comment by JohanLorenzo** [comment]
IIRC, @npark-mozilla said he will look into it. Please correct me if I'm mistaken.

**Comment by nojunpark** [comment]
Yup, working on it, once I'm done checking all taxonomy apis, I'll go back to re-writing this test

**Comment by nojunpark** [comment]
PR #382 handles this one.

**Comment by nojunpark** [comment]
PR #382 is merged now, closing.

**Comment by JohanLorenzo** [comment]
Closed by #382
