### ISSUE TITLE
Philips Hue integration test needs taxonomy port

### ISSUE THREAD

**Issue by cr** [fxbox/foxbox#345]
https://github.com/fxbox/foxbox/pull/332 broke and temporarily disabled the integration test. @npark-mozilla, can you take this?

**Comment by nojunpark** [comment]
@cr sure, all i need is the rest api example in the wiki, (https://wiki.mozilla.org/Connected_Devices/Projects/Project_Link/Taxonomy)

**Comment by Yoric** [comment]
Note that https://github.com/fxbox/foxbox/pull/349 will simplify a little bit the examples.

**Comment by nojunpark** [comment]
PR #382 deals with this one.

**Comment by nojunpark** [comment]
PR #382 is merged now, closing.
