### ISSUE TITLE
Set up page is not scaled properly in adaptable design view

### ISSUE THREAD

**Issue by isabelrios** [fxbox/foxbox#359]
@ferjm, as per our conversation: 
Please see screenshot attached
<img width="318" alt="captura de pantalla 2016-04-13 a las 16 59 11" src="https://cloud.githubusercontent.com/assets/1897507/14498158/b178ff12-0199-11e6-8bc1-db3117b8158d.png">
Thanks!

**Comment by ferjm** [comment]
https://github.com/ferjm/foxbox/commit/066a92e7ad4d31bdf662a7a9388d33fa0e959908
