### ISSUE TITLE
Gate PRs on cross compiling successfully.

### ISSUE THREAD

**Issue by fabricedesre** [fxbox/foxbox#368]
See https://discourse.mozilla-community.org/t/nightly-builds-are-back/8076 for details on the docker image. According to https://docs.travis-ci.com/user/docker/ we should be able to run this image to check that we can cross-compile.

@JohanLorenzo or @npark-mozilla can you take a look at that?

**Comment by JohanLorenzo** [comment]
I'll handle it.
