### ISSUE TITLE
Improve error message `ERROR Connection failed: An error in the OpenSSL library`

### ISSUE THREAD

**Issue by Yoric** [fxbox/foxbox#372]
I suspect that in my case, this mostly means that I failed to provide the authentication token. A clearer error message would be nice.

Cc @samgiles

**Comment by samgiles** [comment]
The auth token isn't related to this, this error happens when a certificate
is not loaded for the host are you requesting, or the client doesn't
support SNI.  Connecting with 'localhost' for example will cause this
error, as you won't have a cert for localhost.

**Comment by Yoric** [comment]
Well, a clearer error message would be nice :)
