### ISSUE TITLE
Once the set up is done foxbox redirects to http instad of https

### ISSUE THREAD

**Issue by isabelrios** [fxbox/foxbox#381]
When the app: https://fxbox.github.io/app is open, it is a secure connection then clicking on Log in button takes to foxbox set up which is also a secure connection[1] but here when clicking on Sing up the app is shown in home view [2], with a connection which is NOT a secure one.
In [1] the query parameter redirect_url is http instead of https

[1] Same when log in not for the first time
<img width="1077" alt="captura de pantalla 2016-04-14 a las 19 31 46" src="https://cloud.githubusercontent.com/assets/1897507/14541314/a9ee3b04-0289-11e6-8044-50549eb5439c.png">
[2]
<img width="1072" alt="captura de pantalla 2016-04-14 a las 19 30 17" src="https://cloud.githubusercontent.com/assets/1897507/14541325/b8830c4e-0289-11e6-8915-ccf04f4f1ab1.png">

**Comment by ferjm** [comment]
Are you sure you start from https?

I just tested and this works for me.

From a local instance exposed via ngrok -> https://gyazo.com/5f03d6936f53a6ca1abba842a3cf0a65
From github pages -> https://gyazo.com/8bda7de9735002dffb035f01f9116fe0

**Comment by isabelrios** [comment]
I start from https but always redirected to http, investigating why...need to confirm my findings but looks more a problem in the app side. We could close this issue if you agree
Thanks!

**Comment by isabelrios** [comment]
Now the apps opens from https and it is kept during the set up and when redirecting back to the app.
Closing the issue.
Thanks!
