### ISSUE TITLE
Call all adapters' stop method when foxbox stops

### ISSUE THREAD

**Issue by julienw** [fxbox/foxbox#387]
Currently we only call `AdapterManager.stop()` which does nothing. Because the Adapter trait provides an default empty `stop` method, we could automatically call all adapters' stop methods.

Note: it's not easy to call the adapters' stop methods from AdapterManager because we don't have an easy access to the adapter objects.

**Comment by Yoric** [comment]
@julienw `AdapterManager.stop()` already calls all the `Adapter.stop()` methods.

**Comment by julienw** [comment]
https://github.com/fxbox/foxbox/blob/master/src/adapters/mod.rs#L75-L76
are you sure ?

**Comment by Yoric** [comment]
Ah, two classes with the same name. Taxonomy's `AdapterManager.stop()` does what you want. So it's only the matter of making Foxbox's `AdapaterManager.stop()` call Taxonomy's.

**Comment by julienw** [comment]
Is it enough to call `taxo_manager.stop()` in https://github.com/fxbox/foxbox/blob/master/src/controller.rs#L102 ?

**Comment by julienw** [comment]
or would you rather pass `&taxo_manager` as a parameter to `adapter_manager.stop`

**Comment by Yoric** [comment]
> Is it enough to call taxo_manager.stop() in https://github.com/fxbox/foxbox/blob/master/src/controller.rs#L102 

Looks good to me.
