### ISSUE TITLE
rustc 2016-04-24 breaks compilation chain

### ISSUE THREAD

**Issue by JohanLorenzo** [fxbox/foxbox#431]
Detected by optional travis jobs against nightly. Aster [can't compile anymore](https://travis-ci.org/fxbox/foxbox/jobs/125659831#L738).
- [last passing](https://travis-ci.org/fxbox/foxbox/jobs/125642813#L367): b5ba5923f 2016-04-21
- [first broken](https://travis-ci.org/fxbox/foxbox/jobs/125659831#L367): 645dd013a 2016-04-24

**Comment by julienw** [comment]
Bug for aster: https://github.com/serde-rs/aster/issues/76
Quasi seems to fail as well, there s no bug there (except an old one that is likely obsolete)

**Comment by JohanLorenzo** [comment]
As @fabricedesre said on IRC, it would be good to include rust-lang/rust#33226 in the next rust up. As of today, the latest version (2016-04-26) doesn't include it.

**Comment by JohanLorenzo** [comment]
Closed by #465
