### ISSUE TITLE
Intermittent: One of the thinkerbell test hangs for more than 10 minutes

### ISSUE THREAD

**Issue by JohanLorenzo** [fxbox/foxbox#439]
It occurs more recurrently these days (I would say 4/10 runs on Travis).  For example, see: https://travis-ci.org/fxbox/foxbox/jobs/126068011#L1466

cc @Yoric

**Comment by Yoric** [comment]
As far as I can tell, it hangs _between_ tests, which makes it hard for me to diagnose.
