### ISSUE TITLE
Selenium tests: Foxbox is not properly killed

### ISSUE THREAD

**Issue by JohanLorenzo** [fxbox/foxbox#451]
# STR
1. `npm run test-selenium` => Notice the tests passing
2. `npm run test-selenium` one more time => Tests are not passing anymore
3. `ps aux | grep foxbox` => 3 instances of foxbox are listed

We likely spawn 2 instances each time we run the tests (one with nodejs and one with the tests). I think I see how to prevent that.

cc FYI @isabelrios @npark-mozilla

**Comment by nojunpark** [comment]
strange, shouldn't that only have 2 instances of foxbox at most?
