### ISSUE TITLE
When channel setter is called with wrong arguments all possible setters are called

### ISSUE THREAD

**Issue by azasypkin** [fxbox/foxbox#502]
While playing with https://github.com/fxbox/foxbox/pull/500 I've accidentally noticed that if we pass wrong selector [1] to the channel setter [2] all possible setters are called. In my case all recipes had been deleted (`remove` setter) and camera made a shot (`camera/store-snapshot` setter).

I didn't have chance to check this on the master, but likely we have this for some time already.

cc @Yoric 

[1] `{"select":{"id":null},"value":{"OnOff":"Off"}}`
[2] `PUT http://local.xxxx.box.knilxof.org:3000/api/v1/channels/set`

**Comment by Yoric** [comment]
I believe that the selector parser is too lenient. Here, it doesn't found anything to parse, so it assumes that we want all channels. This should be pretty easy to fix.

**Comment by Yoric** [comment]
Ah, got it. So, the `id` field in a `ChannelSelector` is a constraint with the type `Exactly<Id<Channel>>`. Passing `null` where there is an `Exactly<_>` is how we can specify "always match". So your selector means "Pick all the channels that have any id". So no bug here, just a confusing case.

I'll try and think of a way to make this less confusing/accident-prone. Since I'm planning on an evolution that will require us to provide the feature whenever we perform a `fetch` or `send` anyway, this might side-solve the problem.

**Comment by azasypkin** [comment]
> So no bug here

Yeah, no coding bug here in its classic sense! But rather the issue with too permissive API that can be too destructive and lead to unrecoverable consequences :)

**Comment by Yoric** [comment]
@azasypkin Not saying that it doesn't need to be fixed :)

Anyway, if you have a chance, could you test-drive the PR I just linked to and see if this solves the issue?

**Comment by azasypkin** [comment]
> Anyway, if you have a chance, could you test-drive the PR I just linked to and see if this solves the issue?

Sure, will give it a try today :)

**Comment by Yoric** [comment]
So, @azasypkin, does it help?

**Comment by azasypkin** [comment]
Grrr, sorry completely forgot about this one. Looking...

**Comment by azasypkin** [comment]
Hmm, is it correct PR (https://github.com/fxbox/foxbox/pull/525) @Yoric ?

I still see the same behavior with request like:
`https://local.609aebe9f46a699f80d6e0284c3334ddf879e125.box.knilxof.org:3000/api/v1/channels/set' -X PUT -H ..... --data-binary '{"select":{"id":null},"value":null}'` - simulated bug in the app when Id of the selected camera is not available for some reason and we pass `null` instead of `take snapshot` channel id.

**Comment by Yoric** [comment]
Oops, right, I had forgotten part of the patch. This should now be fixed.

**Comment by azasypkin** [comment]
Mm, latest PR fails to compile :) https://travis-ci.org/fxbox/foxbox/jobs/138305574
`
src/taxonomy_router.rs:235:40: 235:66 error: type name`ChannelSelectorWithFeature`is undefined or not in scope [E0412]
src/taxonomy_router.rs:235         payload_api!(fetch_values, Vec<ChannelSelectorWithFeature>, ["channels", "get"], Method::Put, binary);
`
