### ISSUE TITLE
Can't generate Let'sEncrypt certificates with outdated letsencrypt.sh script version (Ubuntu 16.04 LTS 64-bit)

### ISSUE THREAD

**Issue by azasypkin** [fxbox/foxbox#528]
Current version of [letsencrypt.sh](https://github.com/fxbox/foxbox/blob/master/components/tls/scripts/letsencrypt.sh) can't parse challenges response correctly (i.e. newlines are not removed from response string and `sed` can't match challenges nodes).

I've checked that the latest version of the script fixes issue for me, so should we just bump it up @samgiles ?

**Comment by samgiles** [comment]
+1, we should definitely keep it up to date
